### ISSUE TITLE
models/to_practice?stats=true doesn't contain predictions (and other stats)

### ISSUE THREAD

**Issue by slaweet** [adaptive-learning/proso-apps#147] opened 2016-05-23 15:37 UTC
Here it doesn't work
http://devel.slepemapy.cz/models/to_practice/?html=true&all=True&filter=%5B%5B%22context%2Fworld%22,%22category%2Friver%22%5D%5D&stats=true

But it works on my localhost:
http://localhost:8000/models/to_practice/?html=true&all=True&filter=%5B%5B%22context%2Fworld%22,%22category%2Friver%22%5D%5D&stats=true

**Comment by papousek** [comment] 2016-05-25 09:18
I am not able to reproduce the issue.

PS: The GET parameter `all=True` is not needed.

**Comment by slaweet** [comment] 2016-05-25 09:28
Now it works for me as well.

**Comment by papousek** [comment] 2016-05-25 20:53
I hope it's fixed by this commit (042cd92956a5be9ab0107ad9823d09f7879a0db5).

**Closed by papousek** 2016-05-25 20:53 UTC
Labels: bug, ready
